// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4mYHxTwm0HlMyJK5m-ltjhEqgj7qRvEw',
    appId: '1:101684591299:web:143e59dcd4df3fc2a54076',
    messagingSenderId: '101684591299',
    projectId: 'eduaf-student-app-2026',
    authDomain: 'eduaf-student-app-2026.firebaseapp.com',
    storageBucket: 'eduaf-student-app-2026.firebasestorage.app',
    measurementId: 'G-CX5LQRFPZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhkFfAJBmgRJIKrNJKZjgacbWb8dEBuFU',
    appId: '1:101684591299:android:1eaf03ad67328d5ea54076',
    messagingSenderId: '101684591299',
    projectId: 'eduaf-student-app-2026',
    storageBucket: 'eduaf-student-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4mYHxTwm0HlMyJK5m-ltjhEqgj7qRvEw',
    appId: '1:101684591299:web:2131ba3df3d674ada54076',
    messagingSenderId: '101684591299',
    projectId: 'eduaf-student-app-2026',
    authDomain: 'eduaf-student-app-2026.firebaseapp.com',
    storageBucket: 'eduaf-student-app-2026.firebasestorage.app',
    measurementId: 'G-DVFT7W4PEG',
  );
}
